name: Trigger Jenkins Pipeline

on:
  workflow_dispatch:  # Trigger manually from the GitHub UI

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest  # Runs on a GitHub-hosted Ubuntu runner
    
    steps:
      - name: Trigger Jenkins Pipeline
        run: |
          # Base64 encode the Jenkins username and API token
          AUTH=$(echo -n "gowthamdronamraju:11eb3dd54a12638df3a2bc7cf630dd8835" | base64)
          
          # Trigger the Jenkins job with authentication
          curl -X POST https://f470-49-206-62-19.ngrok-free.app/job/myfirstpipeline/build \
          -H "Authorization: Basic $AUTH"

